title: Apuntes de Terminal en Linux
description: Material docente para Grado Superior de Desarrollo Web
theme: jekyll-theme-cayman

# Configuración del botón personalizado
show_downloads: true
github:
  zip_url: https://axisalberti.github.io/temario/terminal/
  tar_url: false

# Motor de renderizado de Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins recomendados para compatibilidad con tablas y enlaces relativos
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-optional-front-matter
