otitle: Apuntes de Grado Medio
description: Material docente para Grado Medio
theme: jekyll-theme-cayman



# Motor de renderizado de Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins recomendados para compatibilidad con tablas y enlaces relativos
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-optional-front-matter
