title: Montaje y mantenimiento de equipos informáticos
description: Material de apoyo para alumnos de Grado Medio 
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-optional-front-matter
