title: Apuntes de Terminal en Linux
description: Material de apoyo para alumnos de Grado Superior de Desarrollo Web
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-optional-front-matter
